### ISSUE TITLE
Pre-trained pixel-classifier?

### ISSUE THREAD

**Issue by HOMGH** [yandex-research/ddpm-segmentation#12]
Hi,

Is there any chance to get the pre-trained pixel classifier you trained on your data? Due to high extensive memory usage, I am not able to train the model and just want to evaluate the model. So need the pre-trained MLPs for pixel classification.
That would be amazing if you can share them.
Thanks.

**Comment by dbaranchuk** [comment]
Hey! For what dataset do you need pixel classifiers? I can take a look but it's likely that I've already deleted them

**Comment by ABromide** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MariemOualha** [comment]
Hello , Me too, I also want to get the pretrained interpreter model checkpoint(i.e. pixel_classifier) to play with it

**Comment by ABromide** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mingliutju** [comment]
> Hey! For what dataset do you need pixel classifiers? I can take a look but it's likely that I've already deleted them

Hi, could you provide the pixel classifiers for ffhq_34(DDPM)？

**Comment by dbaranchuk** [comment]
Hey @wwdok @MariemOualha @mingliutju, sorry for the relatively late response. I couldn't find my old checkpoints and hence had to re-run the experiments. Finally, I could get to this and here is the link to the pretrained pixel_classifiers for each dataset: [Dropbox](https://www.dropbox.com/s/kap229jvmhfwh7i/pixel_classifiers.tar?dl=0)

Hope you will find them useful.

**Comment by zhangjh1999** [comment]
Hi,

Is there any chance to get the pre-trained pixel classifier you trained on your data? Due to high extensive memory usage, I am not able to train the model and just want to evaluate the model. So need the pre-trained MLPs for pixel classification.
That would be amazing if you can share them.
Thanks.

> Hey @wwdok @MariemOualha @mingliutju, sorry for the relatively late response. I couldn't find my old checkpoints and hence had to re-run the experiments. Finally, I could get to this and here is the link to the pretrained pixel_classifiers for each dataset: [Dropbox](https://www.dropbox.com/s/zglqj6g0lfxdsg5/pixel_classifiers.tar?dl=0)
> 
> Hope you will find them useful.

This item was delete,can you share them again

**Comment by ABromide** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dbaranchuk** [comment]
@zhangjh1999, the actual link is in the README. I've also updated the link in the corresponding comment here.
