### ISSUE TITLE
datasets.tar.gz 

### ISSUE THREAD

**Issue by duweidai** [yandex-research/ddpm-segmentation#14]
Thank you very much for sharing the code, but we can't download the data (datasets.tar.gz ), can you re-share the download link?
Thank you.

**Comment by dbaranchuk** [comment]
I just checked the link in the README, it should be valid: https://storage.yandexcloud.net/yandex-research/ddpm-segmentation/datasets.tar.gz

**Comment by duweidai** [comment]
> 

Thank you, I have successfully downloaded the data.
