### ISSUE TITLE
How can I train a DDPM model on my own dataset?

### ISSUE THREAD

**Issue by Liareee** [yandex-research/ddpm-segmentation#15]
Hi!
Thank you very much for sharing the code, but I'm a newbie in Diffusion Model. 
I know that the FFHQ-256 is trained by yourself. I would like to try something on other dataset, but I don't know how to do. Can you please share code about how to train a pretrained model on my own dataset ( like CIFAR10 )?

Thank you very much!

**Comment by dbaranchuk** [comment]
There are many pretrained models around and corresponding high-quality implementations. Please refer to https://github.com/openai/guided-diffusion, https://github.com/openai/improved-diffusion, https://github.com/ermongroup/SDEdit. 

For CIFAR10, you can consider https://github.com/NVlabs/edm
