### ISSUE TITLE
What's the scheme for datasets splitting over 5 independent runs?

### ISSUE THREAD

**Issue by yhuang1997** [yandex-research/ddpm-segmentation#16]
Hi,
The work is remarkable, and thank you for sharing your codes!
I wanna reproduce and cite your work but got a question about the scheme for dataset splitting. As said in your paper, all results are from five different dataset splitting. But I found that the downloaded dataset has been split into train & test sets in advance. So, can I combine `train` and `test` and then split them randomly? Is it the right way to use these datasets?
I would appreciate it if you could teach me about these datasets. Thank you!

**Comment by dbaranchuk** [comment]
yes, these 5 splits are obtained randomly as you describe: combine all samples and split randomly. I think it should be fine in your case as well
