### ISSUE TITLE
Question about transform pipeline.

### ISSUE THREAD

**Issue by yhuang1997** [yandex-research/ddpm-segmentation#17]
Hi,
Thanks for sharing your codes.

I'm confused by the transform function of input images: Why are the whole images transformed by `lambda x: x * 2 - 1`.([Here](https://github.com/yandex-research/ddpm-segmentation/blob/82b85580515d5ddc3a6ddb9e6fcbbf11fdb98ef8/src/datasets.py#L16))
I've also tried to discard this transform, and the model goes worse than before. Could you please enlighten me on this question?

Thank you!

**Comment by dbaranchuk** [comment]
Hi, the pretrained diffusion models expect inputs in [-1, 1] ([here](https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/image_datasets.py#L118)). `ToTensor` transforms the image to [0, 1]. `lambda x: x * 2 - 1` --> [-1, 1].
