### ISSUE TITLE
How to define `get_palette` and `get_class_names`, if I want to train on a new dataset?

### ISSUE THREAD

**Issue by CaffreyR** [yandex-research/ddpm-segmentation#19]
Hi, many thanks for your work. I am wondering how to define `get_palette` and `get_class_names`, if I want to train on a new dataset.  Thanks very much!!
https://github.com/yandex-research/ddpm-segmentation/blob/master/src/data_util.py#L1

**Comment by dbaranchuk** [comment]
just define your new palette and class names as dictionaries (similar to [this](https://github.com/yandex-research/ddpm-segmentation/blob/master/src/data_util.py#L36)) and add the corresponding elif branch [here](https://github.com/yandex-research/ddpm-segmentation/blob/master/src/data_util.py#L1).
