### ISSUE TITLE
CelebA weights

### ISSUE THREAD

**Issue by ofirkris** [yandex-research/ddpm-segmentation#2]
Hi, awesome work!
Can you please share a link to download the CelebA weights?

**Comment by dbaranchuk** [comment]
Hi, 

Do you mean DDPM weights? For evaluation on CelebA, we use FFHQ models. So, we didn't train a DDPM on CelebA.

**Comment by dbaranchuk** [comment]
If you still have questions, please feel free to reopen the issue.
