### ISSUE TITLE
Train/Test size used

### ISSUE THREAD

**Issue by JesseWiers** [yandex-research/ddpm-segmentation#21]
Hi, 

I have a question regarding the train/test size used for training the models. In the paper, it is mentioned that: "MLPs are trained on 20 images and evaluated on 20 hold-out ones.". However, later the following table is shown:

<img width="437" alt="Screenshot 2023-03-09 at 14 30 28" src="https://user-images.githubusercontent.com/60656410/224037879-8f956f0b-b606-45b6-acc5-1323396cc514.png">

Could you explain what is meant by this table? Are the models evaluated on more than 20 images?

Thanks,

**Comment by dbaranchuk** [comment]
Hey, "MLPs are trained on 20 images and evaluated on 20 hold-out ones." corresponds to the analysis section only. In main experiments (Section 4), we use the train/test sizes as in the table above.
