### ISSUE TITLE
Datasets and checkpoints for DDPM

### ISSUE THREAD

**Issue by yao-yu1999** [yandex-research/ddpm-segmentation#22]
Hello, the URL:“https://storage.yandexcloud.net/yandex-research/ddpm-segmentation/datasets.tar.gz” link in the sh file cannot be opened， so I can not download it。I would appreciate it if you could send some datasets and  checkpoints to my email address:1720130851@qq.com.

**Comment by dbaranchuk** [comment]
I've just checked the link - it works fine. Maybe it was some network connection issue?
