### ISSUE TITLE
DDPM-based segmentation trained on synthetic images

### ISSUE THREAD

**Issue by lastwhisper-ghy** [yandex-research/ddpm-segmentation#23]
Hi! Thanks for your working and sharing.
I want to know  the way of the DDPM method trained on DDPM-produced data and GAN-produced data. 
Thank you!

**Comment by dbaranchuk** [comment]
Hey, do you mean the experiment in the table 3?

We generated the same nb of random samples with DDPM or GAN for training. Then, we annotated them and repeated the experiments in the same way as for the real data.

**Comment by Ghy1209** [comment]
Hi， can you give me the code of those  experiments? Thank you very much! 
I am the freshman so i am not very good at it.
