### ISSUE TITLE
ModelMeanType

### ISSUE THREAD

**Issue by ZhangXiaotong015** [yandex-research/ddpm-segmentation#24]
Hi, thanks for your sharing.

I was wondering what the '**ModelMeanType**' is in your implementation? It seems that you use the default setting that the diffusion model would predict the noise if I understand you correctly.

**Comment by dbaranchuk** [comment]
Yes, that's right. For our method, we don't use the output of the diffusion model. Thus, ModelMeanType is inherited from the corresponding pretrained models. iirc, it should predict the noise but please check it [here](https://github.com/openai/guided-diffusion).
