### ISSUE TITLE
the best diffusion steps and UNet blocks

### ISSUE THREAD

**Issue by Ghy1209** [yandex-research/ddpm-segmentation#27]
Hi, thanks for your working.
Can you share the best diffusion steps and UNet blocks  using for each task of of DDPM-based segmentation?
By the way, can i use the step 0 ?

**Comment by dbaranchuk** [comment]
the steps and blocks for each dataset are presented in the corresponding config files. These steps are not perfectly tuned but should work fine. 

> can i use the step 0

According to our experiments, the segmentation quality gets worse but it still provides reasonable performance.
