### ISSUE TITLE
How to reproduce the Figure 4. in paper

### ISSUE THREAD

**Issue by StonERMax** [yandex-research/ddpm-segmentation#3]
I have followed the paper to k-means clusters the feature from decoder blocks {6, 8, 10, 12} but l failed. The reproduced result is totally mosaic. And l want to ask whether the code of this part can released. 
<img width="2407" alt="image" src="https://user-images.githubusercontent.com/55312886/163115396-784947d4-2343-4c19-b82a-e0edd555266d.png">

**Comment by dbaranchuk** [comment]
Hi,

Sure, I've released the notebook [here](https://drive.google.com/file/d/14BQXHpt5owQw0-i_FTeflXg2yPFy9VLh/view?usp=sharing). It may have some bad coding practices but should work fine. Hope you find it useful.
