### ISSUE TITLE
Is the reported result based on new setting or old setting?

### ISSUE THREAD

**Issue by Darkbblue** [yandex-research/ddpm-segmentation#32]
Timesteps and blocks used have been adjusted. So which one gives the reported result?

**Comment by dbaranchuk** [comment]
If I remember correctly, I updated the reported results along with the configs. So, the current configs should reproduce the results in the paper.

**Comment by Darkbblue** [comment]
> If I remember correctly, I updated the reported results along with the configs. So, the current configs should reproduce the results in the paper.

Thanks. Then I will try the current configs.
