### ISSUE TITLE
Need more details reproducing Table 2 results

### ISSUE THREAD

**Issue by srk1995** [yandex-research/ddpm-segmentation#34]
Hi, I'm trying to reproduce Table 2 in your paper, but I got a 50.59% mIoU in FFHQ-34, while Table 2 shows 59.1%. Additionally, I obtained a 30.87% mIoU in Bedroom-28, but Table 2 shows 49.4%. Could you please provide more information to help me reproduce your results?

I used an uploaded config file and my system configuration is as follows:

Operating System: Ubuntu 22.04
Python version: 3.7.16
GPU: TITAN RTX
Seed: 0 (default in your code)

Thank you.

**Comment by dbaranchuk** [comment]
Hi, this instruction has to lead to almost perfect reproducibility: https://github.com/yandex-research/ddpm-segmentation#run. Please also consider setting up your environment according to https://github.com/yandex-research/ddpm-segmentation/blob/master/requirements.txt. 

We also provide the pretrained checkpoints [here](https://www.dropbox.com/s/kap229jvmhfwh7i/pixel_classifiers.tar?dl=0), so first you can try to evaluate them.
