### ISSUE TITLE
Some questions about mpi4py

### ISSUE THREAD

**Issue by JawnHoan** [yandex-research/ddpm-segmentation#4]
Hi. Thanks for your work. I had some problems when I was following your work.
In fact, I can't install the "mpi4py". How can I run the code without this requirement?

**Comment by dbaranchuk** [comment]
Hi,

Actually, this requirement comes from the guided_diffusion repo and isn't needed for this code. So, just comment/remove the lines [here](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/dist_util.py#L10) and probably [here](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/image_datasets.py#L6)

**Comment by JawnHoan** [comment]
> Hi,
> 
> Actually, this requirement comes from the guided_diffusion repo and isn't needed for this code. So, just comment/remove the lines [here](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/dist_util.py#L10) and probably [here](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/image_datasets.py#L6)

Thank you very much.
I had solved the problem with your help. But I met a new trouble as follows:

Total dimension 8448
scripts/ddpm/train_interpreter.sh: line 6: 169447 Killed                  python train_interpreter.py --exp experiments/${DATASET}/ddpm.json $MODEL_FLAGS

I found this error in line 57  "X = X.permute(1,0,2,3).reshape(d, -1).permute(1, 0)".  ("train_interpreter.py")
I think my computer with memory 512G is enough to finish this work. My pytorch version is 1.8.0. I don't know if it matters.
